### ISSUE TITLE
Clarifier champ ouvert

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/lieux-covoiturage#14]
La documentation actuelle est peu claire https://github.com/etalab/lieux-covoiturage/blob/be1410a7fb99f04f3e4d5f3db745d4da42256b80/schema.json#L167-L175

Peut être interprété comme :
- actif/inactif
- abrité/non abrité
- fermé par une barrière

**Comment by Miryad3108** [comment]
Sondage lancé sur les réseaux sociaux du 19.01.2022 au 26.01.2022 : https://www.linkedin.com/posts/transportdatagouvfr_le-champ-ouvert-du-sch%C3%A9ma-national-des-activity-6889478503826358272-4mTP

Proposition de Pierre Merce de Bordeaux : rajouter un champ CONDITION D’ACCES : LIBRE/SOUS CONDITION et donner comme définition au champ `ouvert` : en service

**Comment by Miryad3108** [comment]
Après vote par la communauté sur nos réseaux sociaux, la description qui a été retenue est actif/inactif
