### ISSUE TITLE
Fichier exemple-valide.csv invalide

### ISSUE THREAD

**Issue by johanricher** [etalab/lieux-covoiturage#27]
https://validata.fr/table-schema?input=example&schema_url=https://github.com/etalab/lieux-covoiturage/raw/v0.2.7/schema.json&url=https://github.com/etalab/lieux-covoiturage/raw/v0.2.7/exemple-valide.csv

**Comment by AurelienC** [comment]
Le commit f0d7591 corrige le problème de fichier d'exemple invalide
